---
abstract: 'Convert between Latin and Devanagari Sanskrit text'
author:
  - 'glts <676c7473@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-Deva
provides:
  Lingua::Deva:
    file: lib/Lingua/Deva.pm
    version: 1.00
  Lingua::Deva::Aksara:
    file: lib/Lingua/Deva/Aksara.pm
    version: 0
  Lingua::Deva::Maps:
    file: lib/Lingua/Deva/Maps.pm
    version: 0
requires:
  perl: v5.12.1
resources:
  license: http://dev.perl.org/licenses/
version: 1.00
